# Generated by Django 2.2 on 2020-10-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201003_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usermane',
            new_name='username',
        ),
    ]
